package io.cloudbeat.common.model;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

import java.util.*;

public class Instance {
    String id;
    String runId;
    RunStatus status;
    Map<String, String> attributes;
    boolean instanceIdAutoGenerated = false;
    boolean runIdAutoGenerated = false;

    public Instance(final String id, final String runId, Map<String, String> attributes) {
        if (id == null) {
            this.id = UUID.randomUUID().toString();
            instanceIdAutoGenerated = true;
        }
        else
            this.id = id;
        if (runId == null) {
            this.runId = UUID.randomUUID().toString();
            runIdAutoGenerated = true;
        }
        else
            this.runId = runId;
        if (attributes != null)
            this.attributes = attributes;
        else
            this.attributes = new HashMap<>();
    }

    public String getId() {
        return id;
    }

    public String getRunId() {
        return runId;
    }

    public Map<String, String> getAttributes() {
        return attributes;
    }

    public RunStatus getStatus() {
        return  status;
    }

    public void setStatus(RunStatus status) {
        this.status = status;
    }

    public boolean isInstanceIdAutoGenerated() {
        return instanceIdAutoGenerated;
    }

    public boolean isRunIdAutoGenerated() {
        return runIdAutoGenerated;
    }
}
